Rails.application.config.assets.precompile += %w( jquery-1.9.1.min.js )
Rails.application.config.assets.precompile += %w( jquery.jcanvas.min.js )
Rails.application.config.assets.precompile += %w( jquery.bart.js )
Rails.application.config.assets.precompile += %w( classes.js )
Rails.application.config.assets.precompile += %w( painter.js )
Rails.application.config.assets.precompile += %w( stroop.js )
Rails.application.config.assets.precompile += %w( stroop.css )